//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Threading;
using System.Threading.Tasks;
using WhereAreYou.Core.Requests;
using WhereAreYou.Core.Responses;

namespace WhereAreYou.Sso.ApiClient
{
    public interface ISsoApiClient
    {
        Task<Token> EnterTheMeetAsync(EnterTheMeet body);
        Task<Token> EnterTheMeetAsync(EnterTheMeet body, CancellationToken cancellationToken);
    }
}