//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace WhereAreYou.MeetApi.ApiClient
{
    public interface IMeetApiClient
    {
        string BaseUrl { get; set; }
        bool ReadResponseAsString { get; set; }

        Task AddAsync(AddOrUpdatePosition body);
        Task AddAsync(AddOrUpdatePosition body, CancellationToken cancellationToken);
        Task<CreatedMeet> CreateAsync(CreateMeet body);
        Task<CreatedMeet> CreateAsync(CreateMeet body, CancellationToken cancellationToken);
        Task<ICollection<Meet>> GetAllAsync();
        Task<ICollection<Meet>> GetAllAsync(CancellationToken cancellationToken);
        Task<MeetResponse> GetAsync();
        Task<MeetResponse> GetAsync(CancellationToken cancellationToken);
        Task UpdateAsync(AddOrUpdatePosition body);
        Task UpdateAsync(AddOrUpdatePosition body, CancellationToken cancellationToken);
    }
}